footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /rtabmap/proj_map # /map # /rtabmap/proj_map is the rtabmap topic
    subscribe_to_updates: true

# change to realsense sources
obstacles_laser:
    observation_sources: rtabmap_cloud_obstacles rtab_map_cloudXYZ rtab_map_planner_cloud #realsense_laser #realsense_rear_laser #laser # add / remove lidar laser
    #laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}
    #realsense_laser: {data_type: LaserScan, clearing: true, marking: true, topic: realsense/scan, inf_is_valid: true, sensor_frame: base_footprint, min_obstacle_height: -99999.0, max_obstacle_height: 99999.0}
    #realsense_rear_laser: {data_type: LaserScan, clearing: true, marking: true, topic: realsense_rear/scan, inf_is_valid: true, sensor_frame: base_footprint, min_obstacle_height: -99999.0, max_obstacle_height: 99999.0}
    
    # global?? rtab map pointcloud of obsticlaes (stationaly relative to robot)
    rtabmap_cloud_obstacles: {data_type: PointCloud2, clearing: true, marking: true, topic: rtabmap/cloud_obstacles, sensor_frame: base_footprint, min_obstacle_height: -99999.0, max_obstacle_height: 99999.0}
    # generated pointcloud from stereo camera (moves with camera/robot)
    rtab_map_cloudXYZ: {data_type: PointCloud2, clearing: true, marking: true, topic: realsense/cloudXYZ, sensor_frame: base_footprint, min_obstacle_height: -99999.0, max_obstacle_height: 99999.0}
    # local cloud from rtabmap_ros/obstacles_detection node (moves with camera/robot)
    rtab_map_planner_cloud: {data_type: PointCloud2, clearing: true, marking: true, topic: planner_cloud, sensor_frame: base_footprint, min_obstacle_height: -99999.0, max_obstacle_height: 99999.0} # expected_update_rate: 0.5

inflation:
    inflation_radius: 0.2 # default 1.0
