footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /rtabmap/proj_map # /map # /rtabmap/proj_map is the rtabmap topic
    subscribe_to_updates: true

# change to realsense sources
obstacles_laser:
    observation_sources: realsense_laser realsense_rear_laser rtabmap_cloud_obstacles #laser # add / remove lidar laser
    #laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}
    realsense_laser: {data_type: LaserScan, clearing: true, marking: true, topic: realsense/scan, inf_is_valid: true, sensor_frame: base_footprint, min_obstacle_height: -99999.0, max_obstacle_height: 99999.0}
    realsense_rear_laser: {data_type: LaserScan, clearing: true, marking: true, topic: realsense_rear/scan, inf_is_valid: true, sensor_frame: base_footprint, min_obstacle_height: -99999.0, max_obstacle_height: 99999.0}
    rtabmap_cloud_obstacles: {data_type: PointCloud2, clearing: true, marking: true, topic: rtabmap/cloud_obstacles, sensor_frame: base_footprint, min_obstacle_height: -99999.0, max_obstacle_height: 99999.0}

inflation:
    inflation_radius: 0.5 # default 1.0
