obstacle_range: 10.0
raytrace_range: 10.0
footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

map_topic: /map
subscribe_to_updates: true
global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true

static_layer:
    map_topic: /map
    subscribe_to_updates: true

plugins:
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}

obstacle_layer:
    observation_sources: depth_camera
    depth_camera: {sensor_frame: front_realsense, data_type: LaserScan, topic: realsense/scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 2.0, obstacle_range: 10.0, raytrace_range: 10.0}


#max_obstacle_height: 2.0
#inf_is_valid: true

#inflation_radius: 0.5
#costscalingfactor: 1.3

#observation_sources: laser_scan_sensor_merged
#laser_scan_sensor_merged: {sensor_frame: merged_laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}