local_costmap:
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  origin_x: -1.5 # half of cost maps size (width, height so robot is always in centre of cost map)
  origin_y: -1.5
  resolution: 0.1
  inflation_radius: 0.6
  plugins:
      - {name: obstacle_layer,        type: "costmap_2d::VoxelLayer"}



#local_costmap:
#  update_frequency: 5
#  publish_frequency: 5
#  transform_tolerance: 1
#  width: 6
#  height: 6
#  origin_x: -3
#  origin_y: -3
#  static_map: false
#  rolling_window: true
#  resolution: 0.1