# ekf odom to map

# example from https://github.com/mikeferguson/robomagellan/blob/ros2/config/ekf_global.yaml
# and https://automaticaddison.com/sensor-fusion-using-the-ros-robot-pose-ekf-package/

odom_frame: odom
base_link_frame: base_link
world_frame: map
map_frame: map

two_d_mode: true

predict_to_current_time: true

frequency: 50

odom0: /odometry/gps
odom0_config: [true,  true,  false,   # x_pos,    y_pos,     z_pos
               false, false, false,   # roll,     pitch,     yaw
               false, false, false,   # x_vel,    y_vel,     z_vel
               false, false, false,   # roll_vel, pitch_vel, yaw_vel
               false, false, false]   # x_accel,  y_accel,   z_accel
odom0_differential: false
odom0_nodelay: true
odom0_queue_size: 10

odom1: /husky_velocity_controller/odom
odom1_config: [false, false, false,   # x_pos,    y_pos,     z_pos
               false, false, false,   # roll,     pitch,     yaw
               true,  true,  true,    # x_vel,    y_vel,     z_vel
               false, false, true,    # roll_vel, pitch_vel, yaw_vel
               false, false, false]   # x_accel,  y_accel,   z_accel
odom1_differential: false
odom1_queue_size: 10

# only use if using amcl with laser scan /lidaror depth camera
pose0: /amcl_pose
pose0_config: [true, true, false, 
              false, false, true,
              false, false, false, 
              false, false, false,
              false, false, false]
pose0_differential: false
pose0_queue_size: 10

imu0: /imu/data
imu0_config: [false, false, false,   # x_pos,    y_pos,     z_pos
              true,  true,  true,    # roll,     pitch,     yaw
              false, false, false,   # x_vel,    y_vel,     z_vel
              true,  true,  true,    # roll_vel, pitch_vel, yaw_vel
              true,  true,  true]   # x_accel,  y_accel,   z_acce
imu0_differential: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true
