odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: true

predict_to_current_time: true

frequency: 50

odom0: husky_velocity_controller/odom
odom0_config: [false, false, false,   # x_pos,    y_pos,     z_pos
               false, false, false,   # roll,     pitch,     yaw
               true,  true,  true,    # x_vel,    y_vel,     z_vel
               false, false, true,    # roll_vel, pitch_vel, yaw_vel
               false, false, false]   # x_accel,  y_accel,   z_accel
odom0_differential: false
odom0_queue_size: 10

imu0: imu/data
imu0_config: [false, false, false,   # x_pos,    y_pos,     z_pos
              true,  true,  true,    # roll,     pitch,     yaw
              false, false, false,   # x_vel,    y_vel,     z_vel
              true,  true,  true,    # roll_vel, pitch_vel, yaw_vel
              false, false, false]   # x_accel,  y_accel,   z_accel
imu0_differential: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true
